- hosts: nahar
  tasks:
  - name: Adding AppStreamRepository
    yum_repository:
      name: AppStream
      description: AppStream Repository
      baseurl: file:///dvd/AppStream
      #baseurl: file:///run/media/root/RHEL-8-0-0-BaseOS-x86_64/AppStream
      gpgcheck: no 

  - name: Adding BaseOS Repository 
    yum_repository:
      name: BaseOS
      description: BaseOS Repository
      baseurl: file:///dvd/BaseOSSS
      #baseurl: file:///run/media/root/RHEL-8-0-0-BaseOS-x86_64/BaseOS
      gpgcheck: no